// eslint-disable-next-line import/no-anonymous-default-export
export default {
  flashsetTypes: [
    { id: 'fantasy', name: 'Fantasy' },
    { id: 'scifi', name: 'Sci-Fi' },
    { id: 'romance', name: 'Romance' },
    { id: 'horror', name: 'Horror' },
    { id: 'adventure', name: 'Adventure' },
    { id: 'mystery', name: 'Mystery' },
    { id: 'drama', name: 'Drama' },
    { id: 'comedy', name: 'Comedy' },
    { id: 'history', name: 'History' },
    { id: 'biography', name: 'Biography' },
    { id: 'selfhelp', name: 'Self-Help' },
    { id: 'business', name: 'Business' },
    { id: 'technology', name: 'Technology' },
    { id: 'spirituality', name: 'Spirituality' },
    { id: 'healthwellness', name: 'Health & Wellness' },
    { id: 'travel', name: 'Travel' },
    { id: 'education', name: 'Education' },
    { id: 'childrenstories', name: "Children's Stories" },
    { id: 'youngadult', name: 'Young Adult (YA)' },
    { id: 'poetry', name: 'Poetry' },
  ],
  levels: [
    { id: 'sprout_a', name: 'Sprout A' },
    { id: 'sprout_b', name: 'Sprout B' },
    { id: 'bud', name: 'Bud' },
    { id: 'e3', name: 'E3' },
    { id: 'e4', name: 'E4' },
    { id: 'e5', name: 'E5' },
    { id: 'e6', name: 'E6' },
    { id: 'e7', name: 'E7' },
    { id: 'e8', name: 'E8' },
    { id: 'e9', name: 'E9' },
    { id: 'm11', name: 'M11' },
    { id: 'm12', name: 'M12' },
    { id: 'm13', name: 'M13' },
    { id: 'm14', name: 'M14' },
    { id: 'm15', name: 'M15' },
    { id: 'm16', name: 'M16' },
    { id: 'm17', name: 'M17' },
  ],
}
